name: 'Run VM Command'
description: 'Executes a command inside the LVH guest VM via SSH with full color support'
inputs:
  run:
    description: 'The bash command or script to run inside the VM'
    required: true

runs:
  using: "composite"
  steps:
    - name: Execute via SSH
      env:
        FORCE_COLOR: "1"
        TERM: xterm-256color
        CLICOLOR_FORCE: "1"
      run: |
        ssh -tt -p 2222 -o StrictHostKeyChecking=no root@localhost \
          'export BASH_ENV=/host/.github/scripts/lib.sh && ${{ inputs.run }}'
      shell: bash